name: devus
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  go_router: ^15.1.1
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.3
  dio: ^5.8.0+1
  firebase_core: ^3.13.0
  easy_localization: ^3.0.7+1
  validators2: ^5.0.0
  flutter_hooks: ^0.21.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
    - assets/l10n/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic